'use client'
import { useCallback } from 'react'
import {
  ReactFlow,
  Background,
  BackgroundVariant,
  addEdge,
  type Connection,
  type NodeTypes,
} from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { useCanvasStore } from '@/stores/canvasStore'
import { BlockNode } from './nodes/BlockNode'
import { BLOCK_CATALOG, CATALOG_BY_TYPE } from '@/lib/blocks/catalog'
import type { CanvasNode, BlockType } from '@/types'

// Register every defined block type (MVP + stretch) so React Flow can render
// any historical graph loaded from Supabase.
const NODE_TYPES: NodeTypes = Object.fromEntries(
  BLOCK_CATALOG.map((b) => [b.type, BlockNode])
) as NodeTypes

export function Canvas() {
  const {
    nodes,
    edges,
    onNodesChange,
    onEdgesChange,
    setEdges,
    setSelected,
    addNodes,
    pendingNodes,
    pendingEdges,
    pendingTemplate,
    applyStaged,
    rejectStaged,
  } = useCanvasStore()
  const isCopilotSuggested = nodes.some((n) => n.data.source === 'copilot')

  // Union real + pending for rendering. Pending edges get a dashed cyan stroke.
  const renderedNodes = [...nodes, ...pendingNodes]
  const renderedEdges = [
    ...edges,
    ...pendingEdges.map((e) => ({
      ...e,
      animated: false,
      style: { stroke: '#22d3ee', strokeWidth: 1.4, strokeDasharray: '5 4' },
    })),
  ]

  const onNodeClick = useCallback(
    (_: React.MouseEvent, node: { id: string }) => {
      setSelected(node.id)
    },
    [setSelected]
  )

  const onPaneClick = useCallback(() => setSelected(null), [setSelected])

  const onConnect = useCallback(
    (conn: Connection) => {
      if (!conn.source || !conn.target) return
      const next = addEdge(
        {
          id: `e-${conn.source}-${conn.target}-${Date.now()}`,
          source: conn.source,
          target: conn.target,
          sourceHandle: conn.sourceHandle ?? undefined,
          targetHandle: conn.targetHandle ?? undefined,
          data: {},
        },
        edges
      )
      setEdges(next)
    },
    [edges, setEdges]
  )

  const onDrop = useCallback(
    (e: React.DragEvent<HTMLDivElement>) => {
      e.preventDefault()
      const blockType = e.dataTransfer.getData('application/block-type') as BlockType
      if (!blockType) return
      const def = CATALOG_BY_TYPE[blockType]
      if (!def) return
      const bounds = e.currentTarget.getBoundingClientRect()
      const defaultParams = Object.fromEntries(
        def.paramsSchema.map((p) => [p.key, p.default])
      )
      const nodeId = crypto.randomUUID()
      const newNode: CanvasNode = {
        id: nodeId,
        type: blockType,
        position: {
          x: e.clientX - bounds.left - 65,
          y: e.clientY - bounds.top - 30,
        },
        data: {
          id: nodeId,
          name: def.label,
          category: def.category,
          status: 'idle',
          source: 'user',
          blockType: def.type,
          params: defaultParams,
        },
      }
      addNodes([newNode])
    },
    [addNodes]
  )

  const onDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault()
    e.dataTransfer.dropEffect = 'copy'
  }, [])

  return (
    <div
      className="relative w-full h-full"
      onDrop={onDrop}
      onDragOver={onDragOver}
    >
      {isCopilotSuggested && pendingNodes.length === 0 && (
        <div className="absolute top-2.5 left-3 z-10 flex items-center gap-1.5 px-2 py-1 rounded text-[10px] font-mono text-eq-cyan bg-eq-cyan-dim border border-eq-cyan/25">
          <span>✦</span> Generated by Copilot
        </div>
      )}

      {pendingNodes.length > 0 && (
        <div className="absolute top-2.5 left-1/2 -translate-x-1/2 z-20 flex items-center gap-2 px-3 py-1.5 rounded-md bg-bg-2 border border-eq-cyan shadow-lg shadow-black/40">
          <span className="text-[11px] text-eq-cyan font-mono">
            ✦ Copilot suggested {pendingNodes.length} block{pendingNodes.length === 1 ? '' : 's'}
            {pendingTemplate?.name ? ` · ${pendingTemplate.name}` : ''}
          </span>
          <button
            type="button"
            onClick={applyStaged}
            className="px-2.5 py-0.5 rounded bg-eq-cyan text-[#061017] text-[11px] font-semibold hover:brightness-110"
          >
            Apply
          </button>
          <button
            type="button"
            onClick={rejectStaged}
            className="px-2.5 py-0.5 rounded bg-bg-3 text-eq-t2 text-[11px] border border-eq-border-2 hover:text-eq-t1"
          >
            Reject
          </button>
        </div>
      )}

      <div className="absolute bottom-3 right-3 z-10 text-[10px] font-mono text-eq-t3">
        ⌘↵ run · ⌘K copilot
      </div>
      <ReactFlow
        nodes={renderedNodes}
        edges={renderedEdges}
        onNodesChange={onNodesChange}
        onEdgesChange={onEdgesChange}
        onConnect={onConnect}
        onNodeClick={onNodeClick}
        onPaneClick={onPaneClick}
        nodeTypes={NODE_TYPES}
        fitView
        style={{ background: '#0b0d12' }}
        defaultEdgeOptions={{
          style: { stroke: 'rgba(34,211,238,0.25)', strokeWidth: 1.3 },
          animated: false,
        }}
      >
        <Background
          variant={BackgroundVariant.Dots}
          gap={24}
          size={1}
          color="rgba(255,255,255,0.04)"
        />
      </ReactFlow>
    </div>
  )
}
